name: Build and Deploy
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
      - name: Install deps
        run: npm ci
      - name: Build
        run: CI= npm run build
      - name: List output of dist
        run: ls -l build/
      - name: Upload dist to Artifact
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build/
  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download dist from Artifact
        uses: actions/download-artifact@v3
        with:
          name: build
          path: build
      - name: Update
        run: sudo apt-get update
      - name: Add rsync
        run: sudo apt-get install rsync
      - name: Manually add to known hosts
        run: ssh-keyscan -H leadell.agency >> ~/.ssh/known_hosts
      - name: Setup SSH
        uses: MrSquaare/ssh-setup-action@v3
        with:
          host: leadell.agency
          private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Copying
        run: rsync -a --delete build/ alex@35.209.200.246:/home/alex/build

